version: "3"

services:
  graphdb:
    image: dhlabbasel/graphdb-free
    ports:
      - 7200:7200
    depends_on:
      - salsah
    environment:
      - VIRTUAL_HOST=graphdb.localhost
    volumes:
      - ../../graphdb-free/graphdb:/graphdb

  knora:
    image: nieine/knora:22d746e
    ports:
      - 3333:3333
    depends_on:
      - graphdb
    volumes:
      - $HOME:$HOME
      - ../../Knora/tmp/webapi_tmp:/tmp/webapi_tmp/
      - ../../Knora/application.conf:/webapi/config/application.conf
    environment:
      - VIRTUAL_HOST=knora.localhost

  sipi:
    image: nieine/sipi:20171113
    ports:
      - 1024:1024
    volumes:
      - ../tmp:/tmp
      - $HOME:$HOME
      - ../../Sipi/images:/sipi/images
      - ../../Sipi/sipiConfig:/sipi/config
    environment:
      - VIRTUAL_HOST=sipi.localhost

  salsah:
    image: nieine/salsah:7d23855
    volumes:
      - ../../Salsah/environment.ts:/Salsah/src/environments/environment.ts
    ports:
      - 4200:4200
    environment:
      - VIRTUAL_HOST=salsah.localhost
    command: ng serve --host 0.0.0.0 --disable-host-check

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nie-os:
    image: nieine/nie-frontend:devel
    ports:
      - 1234:1234
    environment:
      - NGINX_HOST=nie-os.localhost
      - VIRTUAL_HOST=nie-os.localhost