version: "2"

### THIS IS THE VERSION FOR THE PRODUCTIVE SERVER

services:
#  graphdb:
#    image: dhlabbasel/graphdb-free
#    ports:
#    - 7200:7200
#    depends_on:
#    - salsah
#    volumes:
#    - ../../graphdb-free/graphdb:/graphdb

  knora:
    image: nieine/knora:5-fix
    ports:
    - 3333:3333
#    depends_on:
#    - graphdb
    volumes:
     - $HOME:$HOME
     - ../../tmp/webapi_tmp:/tmp/webapi_tmp/
     - ../../Knora/application.conf:/webapi/config/application.conf
     - ../../tmp/root:/root
     - ../../tmp/root:/var/log
    environment:
     - KNORA_WEBAPI_TRIPLESTORE_HOST=131.152.128.171
     - KNORA_WEBAPI_SIPI_INTERNAL_HOST=sipi
     - KNORA_WEBAPI_TRIPLESTORE_GRAPHDB_REPOSITORY_NAME=knora-test
     - VIRTUAL_HOST=knora2.nie-ine.ch


  sipi:
    image: nieine/sipi:20180828
    ports:
     - "1024:1024"
    volumes:
     - ../../Sipi/sipi/config:/sipi/config
     - ../../Sipi/sipi/scripts:/sipi/scripts
     - ../../tmp:/tmp
     - ../../tmp_import:/tmp_import
     - $HOME:$HOME
     - ../../Sipi/sipi/images:/sipi/images
     - ../../Sipi/sipi/server:/sipi/server
    environment:
     - VIRTUAL_HOST=sipi2.nie-ine.ch
    restart: unless-stopped
    command: --config=/sipi/config/sipi.knora-docker-it-config.lua

  salsah:
    image: nieine/salsah:2de55f5
    ports:
    - 4200:4200
    volumes:
      - ../../Salsah/environment.ts:/Salsah/src/environments/environment.ts
    environment:
      - VIRTUAL_HOST=salsah2.nie-ine.ch
    command: ng serve --host 0.0.0.0 --disable-host-check

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

#  nie-os:
#    image: nieine/nie-frontend:devel
#    ports:
#      - 1234:1234
#    environment:
#      - NGINX_HOST=nie-os.nie-ine.ch
#      - VIRTUAL_HOST=nie-os.nie-ine.ch

  nieos:
    image: nieine/nieos:2019-03
    ports:
    - 4300:4200
    entrypoint: ng s --host 0.0.0.0 --disable-host-check
    environment:
    - VIRTUAL_HOST=test-nieos.nie-ine.ch
    volumes:
    - ./nieOS/src/environments:/nieOS/src/environments

#  node:
#    image: nieine/mean:latest
#    ports:
#    - 4000:3000
#    entrypoint: npm run start:server
#    environment:
#    - VIRTUAL_HOST=node.nie-ine.ch
#    volumes:
#    - ./nieOS/backend/.settings:/nieOS/backend/.settings

