version: "3"

services:
  graphdb:
    image: nieine/graphdb:20180420
    ports:
      - 7200:7200
    depends_on:
      - salsah

  knora:
    image: nieine/knora:c2320fd
    ports:
      - 3333:3333
    depends_on:
      - graphdb
    volumes:
      - ../tmp/webapi_tmp:/tmp/webapi_tmp/

  sipi:
    image: nieine/sipi:20171113
    ports:
      - 1024:1024
    volumes:
      - ../tmp:/tmp
      - $HOME:$HOME
      - ../Sipi/images:/sipi/images
      - ../sipiConfig:/sipi/config

  salsah:
    image: nieine/salsah:5fba91e
    ports:
      - 4200:4200